language: generic
os: linux
services:
    - docker
before_install:
    - docker build -t marlonmacf/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true marlonmacf/docker-react npm run test